import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
    // Ana Container
    container: {
        flex: 1,
        backgroundColor: '#F8FAFC',
    },

    // Header Bölümü
    header: {
        paddingHorizontal: 20,
        paddingVertical: 16,
        backgroundColor: '#FFFFFF',
        borderBottomWidth: 0,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.06,
        shadowRadius: 8,
        elevation: 3,
    },
    title: {
        fontSize: 26,
        fontWeight: '800',
        color: '#1F2937',
        textAlign: 'center',
        flex: 1,
        letterSpacing: -0.5,
    },
    backButton: {
        padding: 8,
        borderRadius: 8,
        backgroundColor: '#F3F4F6',
    },
    placeholder: {
        width: 40,
    },
    subtitle: {
        fontSize: 16,
        color: '#6B7280',
        textAlign: 'center',
        marginTop: 8,
        fontWeight: '500',
    },

    // Input Bölümü
    inputContainer: {
        paddingHorizontal: 20,
        marginVertical: 10,
        backgroundColor: '#FFFFFF',
        borderBottomWidth: 1,
        borderBottomColor: '#E9ECEF',
    },
    inputRow: {
        alignItems: 'center',
        marginBottom: 16,
        flexDirection: 'row',

    },
    input: {
        flex: 1,
        height: 50,
        borderWidth: 1,
        borderColor: '#ddd',
        borderRadius: 7,
        paddingHorizontal: 15,
        fontSize: 16,
        backgroundColor: '#FFFFFF',
        color: '#374151',
    },
    addButton: {
        width: 50,
        height: 50,
        borderRadius: 7,
        justifyContent: 'center',
        alignItems: 'center',
        marginLeft: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 4,
    },

    // Seçenekler Satırı
    optionsRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 10,
    },
    colorSelector: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 10,
        height: 70,
        backgroundColor: '#F8F9FA',
        width: '48%',
        borderWidth: 1,
        borderColor: '#ddd',
        borderRadius: 7,
    },
    dateSelector: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: 10,
        backgroundColor: '#F8F9FA',
        width: '48%',
        borderWidth: 1,
        borderColor: '#ddd',
        borderRadius: 7,
    },
    colorPreview: {
        width: 24,
        height: 24,
        borderRadius: 5,
        marginRight: 10,

    },
    colorSelectorText: {
        fontSize: 16,
        color: '#666',

    },
    dateSelectorText: {
        fontSize: 16,
        color: '#666',
        marginLeft: 10,
    },

    // Kategori ve Filtre Seçicileri
    categorySelector: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 10,
        backgroundColor: '#F8F9FA',
        marginLeft: 10,
        height: 70,
        width: '48%',
        borderWidth: 1,
        borderColor: '#ddd',
        borderRadius: 7,
    },
    categorySelectorText: {
        flex: 1,
        fontSize: 16,
        color: '#666',
        marginLeft: 10,
    },
    filterSelector: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 10,
        backgroundColor: '#F8F9FA',
        marginLeft: 10,
        width: '48%',
        borderWidth: 1,
        borderColor: '#ddd',
        borderRadius: 7,
    },
    filterSelectorText: {
        flex: 1,
        fontSize: 16,
        color: '#666',
        marginLeft: 10,
    },
    categoryText: {
        fontSize: 12,
        fontWeight: '700',
        letterSpacing: 0.3,
    },

    // Renk Seçici
    colorPickerContainer: {
        paddingHorizontal: 20,
        paddingVertical: 20,
        backgroundColor: '#FFFFFF',
        borderBottomWidth: 0,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.08,
        shadowRadius: 12,
        elevation: 4,
    },
    colorPickerTitle: {
        fontSize: 20,
        fontWeight: '800',
        color: '#1F2937',
        marginBottom: 20,
        letterSpacing: -0.3,
    },
    colorItemContainer: {
        alignItems: 'center',
        margin: 6,
    },
    colorGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'center',
        alignItems: 'flex-start',
        marginTop: 12,
    },
    colorName: {
        fontSize: 12,
        marginTop: 8,
        textAlign: 'center',
        color: '#6B7280',
        fontWeight: '500',
    },
    colorOption: {
        width: 48,
        height: 48,
        borderRadius: 24,
        margin: 6,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.1,
        shadowRadius: 6,
        elevation: 4,
    },
    selectedColor: {
        borderWidth: 1,
        borderColor: '#000',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 6,
    },

    // Todo Listesi
    todoList: {
        flex: 1,
        paddingHorizontal: 10,
        paddingVertical: 10,
    },
    todoItem: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: 10,
        borderRadius: 9,
        margin: 10,
        elevation: 4,
        borderBottomWidth: 0,

    },
    todoContent: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    todoTextContainer: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'flex-start',
    },
    checkIcon: {
        marginRight: 10,
        marginTop: 2,
    },
    todoTextWrapper: {
        flex: 1,
    },
    todoText: {
        fontSize: 16,
        flex: 1,
        fontWeight: '600',
        marginBottom: 8,
        lineHeight: 22,
        color: '#1F2937',
    },
    dueDateText: {
        fontSize: 13,
        opacity: 0.7,
        fontWeight: '500',
        letterSpacing: 0.2,
        color: '#6B7280',
    },
    completedText: {
        textDecorationLine: 'line-through',
        opacity: 0.5,
        textDecorationColor: '#9CA3AF',
        color: '#9CA3AF',
    },
    todoActions: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    actionButton: {
        padding: 8,
        marginLeft: 12,
    },

    // Boş Durum
    emptyState: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 80,
    },
    emptyText: {
        fontSize: 20,
        color: '#6B7280',
        marginTop: 24,
        fontWeight: '700',
        letterSpacing: -0.3,
    },
    emptySubtext: {
        fontSize: 16,
        color: '#9CA3AF',
        marginTop: 12,
        textAlign: 'center',
        fontWeight: '500',
        lineHeight: 22,
    },

    // Arama Tuşu
    searchToggleButton: {
        position: 'absolute',
        top: Platform.OS === 'ios' ? 109 : 68,
        left: 10,
        width: 25,
        height: 30,
        backgroundColor: '#6366F1',
        borderBottomLeftRadius: Platform.OS === 'ios' ? 25 : 20,
        borderBottomRightRadius: Platform.OS === 'ios' ? 25 : 20,
        justifyContent: 'center',
        alignItems: 'center',
        ...Platform.select({
            ios: {
                shadowColor: '#000',
                shadowOffset: { width: 0, height: 2 },
                shadowOpacity: 0.2,
                shadowRadius: 4,
            },
            android: {
                elevation: 6,
            },
        }),
        zIndex: 1000,
    },

    // Arama Çubuğu
    searchContainer: {
        marginTop: 10,
        paddingHorizontal: 20,
    },
    searchRow: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F9FAFB',
        borderWidth: 1,
        borderColor: '#E5E7EB',
        borderRadius: 8,
        paddingHorizontal: 10,
        gap: 10,
    },
    searchInput: {
        flex: 1,
        height: 40,
        paddingHorizontal: 15,
        fontSize: 14,
        color: '#374151',
    },
    searchClearButton: {
        padding: 8,
        borderRadius: 8,
        backgroundColor: '#F3F4F6',
    },

    // Gelişmiş Filtreleme
    filterSection: {
        marginBottom: 20,
    },
    filterSectionTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: '#1F2937',
        marginBottom: 10,
        paddingHorizontal: 20,
    },
    filterChip: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 15,
        backgroundColor: '#F3F4F6',
        marginRight: 8,
        marginBottom: 8,
    },
    filterChipText: {
        fontSize: 14,
        color: '#374151',
        fontWeight: '500',
        marginLeft: 6,
    },
    activeFilterChip: {
        backgroundColor: '#6366F1',
    },
    activeFilterChipText: {
        color: 'white',
    },

    // Öncelik Göstergesi
    priorityIndicator: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 12,
        backgroundColor: 'rgba(0,0,0,0.1)',
        marginLeft: 8,
    },
    priorityText: {
        fontSize: 12,
        fontWeight: '600',
        marginLeft: 4,
    },

    // İstatistikler
    stats: {
        paddingHorizontal: 20,
        paddingVertical: 16,
        backgroundColor: '#FFFFFF',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -2 },
        shadowOpacity: 0.04,
        shadowRadius: 6,
        elevation: 3,
    },
    statsText: {
        textAlign: 'center',
        fontSize: 14,
        color: '#6B7280',
        fontWeight: '600',
        letterSpacing: 0.2,
    },

    // Modal Stilleri
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContent: {
        backgroundColor: '#FFFFFF',
        borderRadius: 20,
        padding: 24,
        width: '90%',
        maxWidth: 340,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 12 },
        shadowOpacity: 0.25,
        shadowRadius: 24,
        elevation: 12,
    },
    modalTitle: {
        fontSize: 22,
        fontWeight: '800',
        color: '#1F2937',
        textAlign: 'center',
        marginBottom: 24,
        letterSpacing: -0.3,
    },
    dateOption: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#F3F4F6',
        borderRadius: 8,
        marginBottom: 4,
    },
    dateOptionText: {
        fontSize: 16,
        color: '#1F2937',
        fontWeight: '600',
    },
    cancelButton: {
        marginTop: 20,
        padding: 16,
        backgroundColor: '#F9FAFB',
        borderRadius: 12,
        alignItems: 'center',
        borderWidth: 0,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.04,
        shadowRadius: 4,
        elevation: 2,
    },
    cancelButtonText: {
        fontSize: 16,
        color: '#374151',
        fontWeight: '700',
    },

    // Takvim Stilleri
    calendarHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingVertical: 10,
        backgroundColor: '#FFFFFF',
        borderBottomWidth: 0,
        borderRadius: 7,
        margin: 20,
        elevation: 4,
    },
    monthButton: {
        padding: 12,
        borderRadius: 8,
        backgroundColor: '#f1f1f1',
    },
    monthTitle: {
        fontSize: 24,
        fontWeight: '800',
        color: '#1F2937',
        letterSpacing: -0.3,
    },
    weekDays: {
        flexDirection: 'row',
        backgroundColor: '#FFFFFF',
        padding: 10,
        borderBottomWidth: 0,
        marginHorizontal: 20,
        borderRadius: 12,
        marginBottom: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.04,
        shadowRadius: 4,
        elevation: 2,
    },
    weekDay: {
        flex: 1,
        textAlign: 'center',
        fontSize: 14,
        fontWeight: '700',
        color: '#6B7280',
        letterSpacing: 0.2,
    },
    calendarGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        backgroundColor: '#FFFFFF',
        padding: 12,
        borderRadius: 16,
        margin: 20,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 0.06,
        shadowRadius: 8,
        elevation: 6,
    },
    calendarDay: {
        width: '14.28%',
        aspectRatio: 1,
        justifyContent: 'center',
        alignItems: 'center',
        position: 'relative',
        margin: 3,
        height: 25,
        borderRadius: 7,
    },
    otherMonthDay: {
        opacity: 0.4,
    },
    selectedDay: {
        backgroundColor: '#6366F1',
        borderRadius: 7,
        shadowColor: '#6366F1',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.3,
        shadowRadius: 6,
        elevation: 5,
    },
    hasTodosDay: {
        backgroundColor: '#ddffdd',
        borderRadius: 7,
        borderWidth: 2,
        borderColor: '#a6cc9b',
    },
    todayDay: {
        backgroundColor: '#6366F1',
        borderRadius: 7,
        borderWidth: 2,
        borderColor: '#4338CA',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.3,
        shadowRadius: 6,
        elevation: 5,
    },
    dayText: {
        fontSize: 16,
        color: '#1F2937',
        fontWeight: '600',
    },
    otherMonthText: {
        color: '#D1D5DB',
        opacity: 0.6,
    },
    selectedDayText: {
        color: 'white',
        fontWeight: '700',
    },
    todayText: {
        color: 'white',
        fontWeight: '700',
    },
    todoIndicator: {
        position: 'absolute',
        bottom: 3,
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: '#3730A3',
    },
    calendarFooter: {
        paddingHorizontal: 20,
        paddingVertical: 16,
        backgroundColor: '#FFFFFF',
        borderTopWidth: 0,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -2 },
        shadowOpacity: 0.04,
        shadowRadius: 6,
        elevation: 3,
    },
    calendarFooterText: {
        textAlign: 'center',
        fontSize: 14,
        color: '#6B7280',
        marginBottom: 8,
        fontWeight: '600',
        letterSpacing: 0.2,
    },
});